import { contextBridge, ipcRenderer } from 'electron';
import type { ClaudeUiApi } from '../shared/types';
import type { LayoutReport, PanelData, PanelRunEvent } from '../shared/panels';
import type { SettingsView } from '../shared/settings';

const api: ClaudeUiApi = {
  listSessions: () => ipcRenderer.invoke('sessions:list'),
  getHistory: (id, known, generation) => ipcRenderer.invoke('history:get', id, known, generation),
  worktreeExists: (repoRoot, name) => ipcRenderer.invoke('sessions:worktreeExists', repoRoot, name),
  onSessionsChanged: (callback) => ipcRenderer.on('sessions:changed', () => callback()),
  onQuitting: (callback) => ipcRenderer.on('app:quitting', () => callback()),
  onClaudeMissing: (callback) => ipcRenderer.on('app:claude-missing', () => callback()),
  getPinned: () => ipcRenderer.invoke('meta:getPinned'),
  togglePin: (id) => ipcRenderer.invoke('meta:togglePin', id),
  getHistoryPins: () => ipcRenderer.invoke('meta:getHistoryPins'),
  toggleHistoryPin: (id, pin) => ipcRenderer.invoke('meta:toggleHistoryPin', id, pin),
  getArchived: () => ipcRenderer.invoke('meta:getArchived'),
  toggleArchive: (id) => ipcRenderer.invoke('meta:toggleArchive', id),
  deleteSession: (id) => ipcRenderer.invoke('sessions:delete', id),
  getOpenSessions: () => ipcRenderer.invoke('meta:getOpenSessions'),
  setOpenSessions: (ids, running) => ipcRenderer.send('meta:setOpenSessions', ids, running),
  getRunningSessions: () => ipcRenderer.invoke('meta:getRunningSessions'),
  getActiveSession: () => ipcRenderer.invoke('meta:getActiveSession'),
  getActiveSessionByProject: () => ipcRenderer.invoke('meta:getActiveSessionByProject'),
  setActiveSession: (id, repoRoot) => ipcRenderer.send('meta:setActiveSession', id, repoRoot),
  getActiveProject: () => ipcRenderer.invoke('meta:getActiveProject'),
  setActiveProject: (folder) => ipcRenderer.send('meta:setActiveProject', folder),
  getNotes: () => ipcRenderer.invoke('meta:getNotes'),
  setNote: (id, note) => ipcRenderer.invoke('meta:setNote', id, note),
  getUiState: () => ipcRenderer.invoke('meta:getUiState'),
  setUiState: (state) => ipcRenderer.send('meta:setUiState', state),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setSettings: (change) => ipcRenderer.invoke('settings:set', change),
  onSettingsChanged: (callback) => ipcRenderer.on('settings:changed', (_event, view: SettingsView) => callback(view)),
  getWindowChrome: () => ipcRenderer.invoke('window:chrome'),
  minimizeWindow: () => ipcRenderer.send('window:minimize'),
  toggleMaximizeWindow: () => ipcRenderer.send('window:toggleMaximize'),
  closeWindow: () => ipcRenderer.send('window:close'),
  startWindowResize: (edge, pointer) => ipcRenderer.send('window:resizeStart', edge, pointer),
  resizeWindowBy: (dx, dy) => ipcRenderer.send('window:resizeBy', dx, dy),
  endWindowResize: () => ipcRenderer.send('window:resizeEnd'),
  onWindowMaximized: (handler) => ipcRenderer.on('window:maximized', (_event, maximized: boolean) => handler(maximized)),
  getProjectNames: () => ipcRenderer.invoke('meta:getProjectNames'),
  setProjectName: (repoRoot, name) => ipcRenderer.invoke('meta:setProjectName', repoRoot, name),
  getGroupState: () => ipcRenderer.invoke('meta:getGroupState'),
  createGroup: (name, repoRoot, sessionId) => ipcRenderer.invoke('meta:createGroup', name, repoRoot, sessionId),
  renameGroup: (id, name) => ipcRenderer.invoke('meta:renameGroup', id, name),
  deleteGroup: (id) => ipcRenderer.invoke('meta:deleteGroup', id),
  moveSessionToGroup: (sessionId, groupId) => ipcRenderer.invoke('meta:moveSessionToGroup', sessionId, groupId),
  recordClear: (from, to, title) => ipcRenderer.invoke('meta:recordClear', from, to, title),
  moveGroup: (id, move) => ipcRenderer.invoke('meta:moveGroup', id, move),
  getProjectOrder: () => ipcRenderer.invoke('meta:getProjectOrder'),
  seedProjectOrder: (roots) => ipcRenderer.invoke('meta:seedProjectOrder', roots),
  moveProject: (repoRoot, move) => ipcRenderer.invoke('meta:moveProject', repoRoot, move),
  pickFolder: () => ipcRenderer.invoke('dialog:pickFolder'),
  openExternal: (url) => ipcRenderer.send('shell:openExternal', url),
  getAllStatuses: () => ipcRenderer.invoke('status:getAll'),
  onSessionStatus: (callback) =>
    ipcRenderer.on('session:status', (_event, id: string, status: string, tab: string, event: string) => callback(id, status, tab, event)),
  onSessionModel: (callback) =>
    ipcRenderer.on('session:model', (_event, id: string, model: string) => callback(id, model)),
  clearStatus: (id) => ipcRenderer.send('status:clear', id),
  startTerminal: (cwd, launch) => ipcRenderer.invoke('terminal:start', cwd, launch),
  startShell: (cwd, context) => ipcRenderer.invoke('terminal:startShell', cwd, context),
  onTerminalData: (callback) =>
    ipcRenderer.on('terminal:data', (_event, id: number, data: string) => callback(id, data)),
  onTerminalExit: (callback) =>
    ipcRenderer.on('terminal:exit', (_event, id: number, exitCode: number) => callback(id, exitCode)),
  sendTerminalInput: (id, data) => ipcRenderer.send('terminal:input', id, data),
  resizeTerminal: (id, cols, rows) => ipcRenderer.send('terminal:resize', id, cols, rows),
  killTerminal: (id) => ipcRenderer.send('terminal:kill', id),
  closeTerminal: (id, interrupt) => ipcRenderer.send('terminal:close', id, interrupt),
  getLayout: () => ipcRenderer.invoke('config:getLayout'),
  checkPath: (value, base, must) => ipcRenderer.invoke('config:checkPath', value, base, must),
  onLayoutChanged: (callback) => ipcRenderer.on('config:changed', (_event, report: LayoutReport) => callback(report)),
  setLayoutState: (changes) => ipcRenderer.invoke('config:setLayoutState', changes),
  moveLayoutState: (nodes) => ipcRenderer.invoke('config:moveLayoutState', nodes),
  runPanel: (request) => ipcRenderer.send('panel:run', request),
  stopPanel: (entryId) => ipcRenderer.send('panel:stop', entryId),
  onPanelRun: (callback) =>
    ipcRenderer.on('panel:run', (_event, entryId: string, token: string, event: PanelRunEvent) =>
      callback(entryId, token, event),
    ),
  getPanelData: (entryId) => ipcRenderer.invoke('panelData:get', entryId),
  linkPanelSession: (entryId, sessionId, link, filed) => ipcRenderer.invoke('panelData:link', entryId, sessionId, link, filed),
  onPanelDataChanged: (callback) => ipcRenderer.on('panelData:changed', (_event, entryId: string, data: PanelData) => callback(entryId, data)),
  getFolders: () => ipcRenderer.invoke('folders:get'),
  openFolder: (name) => ipcRenderer.send('folder:open', name),
  log: (level, area, message) => ipcRenderer.send('log:write', level, area, message),
};

contextBridge.exposeInMainWorld('claudeUi', api);
